#!/usr/bin/env sh
mkdir -p tmp
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
curl https://integration-api.meshconnect.com/swagger/v1/swagger.json > tmp/openapi.json
echo "/**
 * Generated by tasks/generate_mesh_client.sh
 */" > mesh/Generated.ts
./node_modules/.bin/openapi-gen -s tmp/openapi.json >> experimental_client/Generated.ts
dprint fmt
# git apply $SCRIPT_DIR/create-chat-completions-response.patch